version: '3.1'

networks:
  wpp:
    driver: bridge

services:
    wordpress:
        container_name: wpp-website-local
        image: wpp-custom-wordpress-local
        networks:
          - wpp
        build:
          context: wordpress/build
          args:
            DEBUG_SUPPORT: "true" # builds an image with/without debug support (xdebug)
        ports:
          - 5003:80
        environment:
          WORDPRESS_DB_PASSWORD: admin
          SITE_URL: http://localhost:5003
          ENABLE_DEBUG: "true" # enable/disable debug mode in wordpress at run time
        volumes:
          - ./wordpress/wp-content:/var/www/html/wp-content
          - ./webapp:/var/www/webapp
    mysql:
        container_name: wpp-mysql-local
        image: wpp-custom-mysql-local
        networks:
          - wpp
        build:
          context: mysql/
          args:
            IMPORT_DB: "true" # Remember: the import will only work if the wordpress/db dir is empty
            MYSQL_ROOT_PASS: admin # Used during the build and internally is defined as ENV MYSQL_ROOT_PASSWORD
        volumes:
          - ./wordpress/db:/var/lib/mysql
    adminer:
      image: adminer
      container_name: wpp-adminer
      networks:
        - wpp
      ports:
        - 5001:8080
