version: '3.1'

networks:
  wpp-imoveis-staging:
    driver: bridge

services:
    wordpress:
        container_name: wpp-imoveis-staging
        image: wpp-imoveis-custom-wordpress-staging
        networks:
          - wpp-imoveis-staging
        restart: always
        build:
          context: wordpress/build
          args:
            DEBUG_SUPPORT: "false"
        ports:
          - 8090:80        
        environment:
          WORDPRESS_DB_PASSWORD: admin
          SITE_URL: http://imoveis-staging.fazendoasmalas.com
          ENABLE_DEBUG: "false" # enable/disable debug mode in wordpress at run time     
        volumes:
          - ./wordpress/wp-content:/var/www/html/wp-content
          - ./webapp:/var/www/webapp
    mysql:
        container_name: wpp-imoveis-mysql-staging
        image: wpp-imoveis-custom-mysql-staging
        networks:
          - wpp-imoveis-staging
        restart: always
        build:
          context: mysql/
          args:
            IMPORT_DB: "true" # Remember: the import will only work if the wordpress/db dir is empty
            MYSQL_ROOT_PASS: admin # Used during the build and internally is defined as ENV MYSQL_ROOT_PASSWORD
        volumes:
          - ./wordpress/db:/var/lib/mysql
